package com.muvasia.driver.androidarchitecturecomponents.database

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/** 
 * Immutable model class for a Note and entity in the Room Database
 *
 * @param title     title of the note
 * @param body      body/description of the note
 */
@Entity(tableName = "notes")
class Note(title: String, body: String) {

    //  Note id will be autogenerated
    @PrimaryKey(autoGenerate = true)
    var id: Int = 0

    @ColumnInfo(name = "title")
    var title: String? = title

    @ColumnInfo(name = "body")
    var body: String? = body

}

